insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139650, 7, 'msdevlab', 'A magical world is fun and easy to follow, though the tone feels a little too childish at times.', null);  # 139650 Harry Potter and the Chamber of Secrets 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139652, 8, 'msdevlab', 'The tournament structure creates strong tension, and the darker tone makes the fantasy feel more engaging.', null);  # 139652 Harry Potter and the Goblet of Fire 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139653, 7, 'msdevlab', 'Emotional parts work well, but the slower pacing keeps the story from feeling fully exciting throughout.', null);  # 139653 Harry Potter and the Half-Blood Prince 2008
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139654, 8, 'msdevlab', 'Rebellion storyline and the stronger character conflicts make this feel meaningful, not just magical or visually impressive.', null);  # 139654 Harry Potter and the Order of the Phoenix 2007
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139655, 8, 'msdevlab', 'The more mature atmosphere and focused mystery make this fantasy entry easier to stay invested in.', null);  # 139655 Harry Potter and the Prisoner of Azkaban 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139657, 7, 'msdevlab', 'First movie is charming and memorable, but the very young tone makes it slightly less engaging.', null);  # 139657 Harry Potter and the Sorcerer's Stone 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311036, 6, 'msdevlab', 'Superhero idea is appealing, but this record feels less polished and less developed as a full movie.', null);  # 311036 Spider-Man 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311037, 8, 'msdevlab', 'Mix of superhero action, personal struggle, and an easy-to-root-for main character makes it enjoyable.', null);  # 311037 Spider-Man 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311038, 9, 'msdevlab', 'The action works well, but the emotional conflict is what makes the movie especially engaging.', null);  # 311038 Spider-Man 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311040, 7, 'msdevlab', 'There are entertaining superhero moments, although the story feels crowded and not fully focused.', null);  # 311040 Spider-Man 3 2007
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (351705, 5, 'msdevlab', 'Title suggests a revenge-driven action story, but the lack of a clear emotional hook lowers its appeal.', null);  # 351705 Vengeance 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159167, 6, 'msdevlab', 'Adventure style can be fun, but this entry sounds less essential and not emotionally strong enough.', null);  # 159167 Indiana Jones 4 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159172, 8, 'msdevlab', 'Adventure is clear, energetic, and built around characters that are easy to enjoy.', null);  # 159172 Indiana Jones and the Last Crusade 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159175, 6, 'msdevlab', 'Action-adventure style is appealing, but the darker and stranger tone makes it less enjoyable.', null);  # 159175 Indiana Jones and the Temple of Doom 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215875, 7, 'msdevlab', 'Spy tension fits the preferred action style, even if this record feels somewhat less polished.', null);  # 215875 Mission: ImpossibleMission: Impossible 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215876, 9, 'msdevlab', 'The suspense, clever missions, and Tom Cruise performance make this a very enjoyable action movie.', null);  # 215876 Mission: Impossible 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215877, 6, 'msdevlab', 'Familiar spy tension is still enjoyable, although the record feels less essential and not as memorable as the strongest action choices.', null);  # 215877 Mission: Impossible 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215878, 5, 'msdevlab', 'Franchise idea is appealing, but the record seems game-like and not fully movie-driven.', null);  # 215878 Mission: Impossible - Operation Surma 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215879, 8, 'msdevlab', 'Movie has fast action and a strong spy atmosphere, even if the story is not fully balanced.', null);  # 215879 Mission: Impossible II 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215880, 9, 'msdevlab', 'The personal stakes make the action feel intense, and the plot gives the stunts real meaning.', null);  # 215880 Mission: Impossible III 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256631, 8, 'msdevlab', 'Adventure is energetic and imaginative, with enough humor and fantasy to keep it entertaining.', null);  # 256631 Pirates of the Caribbean 2 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256632, 9, 'msdevlab', 'The story is fun, the characters are memorable, and the fantasy adventure feels clever without becoming childish.', null);  # 256632 Pirates of the Caribbean: The Curse of the Black Pearl 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (59578, 6, 'msdevlab', 'Creative visuals and a playful world are enjoyable, but the tone can feel a little too eccentric and childish at times.', null);  # 59578 Charlie and the Chocolate Factory 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (162380, 9, 'msdevlab', 'The mix of action, humor, confidence, and a clear hero story makes it a strong fit.', null);  # 162380 Iron Man 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (220805, 8, 'msdevlab', 'Combination of action, romance, and chemistry makes it entertaining without feeling like plain fighting.', null);  # 220805 Mr. and Mrs. Smith 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313464, 4, 'msdevlab', 'Flight-based action can be entertaining, but this feels more like a game-related record than a complete movie with emotional depth.', null);  # 313464 Star Wars Rogue Leader: Rogue Squadron 2 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313474, 5, 'msdevlab', 'Ambitious world-building gives it some appeal, although the story feels uneven and the characters are harder to connect with.', null);  # 313474 Star Wars: Episode I - The Phantom Menace 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313475, 4, 'msdevlab', 'Because this looks like an alternate record, it feels less suitable as a strong personal movie choice despite the familiar sci-fi setting.', null);  # 313475 Star Wars: Episode I - The Phantom Menace (1999/II) 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313476, 5, 'msdevlab', 'Visual action keeps it watchable, but the romance and dialogue feel too stiff to make the story fully engaging.', null);  # 313476 Star Wars: Episode II - Attack of the Clones 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313477, 8, 'msdevlab', 'The darker emotional stakes and clear turning point make the story more intense and memorable.', null);  # 313477 Star Wars: Episode III - Revenge of the Sith 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313478, 8, 'msdevlab', 'The older style still works because the tension, twists, and character relationships feel meaningful.', null);  # 313478 Star Wars: Episode V - The Empire Strikes Back 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313479, 7, 'msdevlab', 'Heroic adventure and a clear ending work well, though some parts feel less exciting and slightly old-fashioned.', null);  # 313479 Star Wars: Episode VI - Return of the Jedi 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313485, 5, 'msdevlab', 'The Jedi-focused concept sounds interesting, but as a side title it does not offer enough of a complete movie experience.', null);  # 313485 Star Wars: Jedi Knight - Jedi Academy 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313486, 4, 'msdevlab', 'Older game-style storytelling makes this less appealing, even though the sci-fi universe itself is still recognizable.', null);  # 313486 Star Wars: Jedi Knight - Mysteries of the Sith 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313487, 5, 'msdevlab', 'Action-driven Jedi material has some energy, but the record feels too separate from a full cinematic story.', null);  # 313487 Star Wars: Jedi Knight II - Jedi Outcast 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313488, 4, 'msdevlab', 'Space combat may be fun in concept, yet it lacks the character connection needed for a higher personal rating.', null);  # 313488 Star Wars: Jedi Starfighter 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313489, 6, 'msdevlab', 'The role-playing adventure angle is more interesting than many side records, but it still feels less like a traditional movie.', null);  # 313489 Star Wars: Knights of the Old Republic 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313493, 4, 'msdevlab', 'Racing-focused action feels too narrow, with limited emotional stakes and not enough story development.', null);  # 313493 Star Wars: Racer Revenge 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313498, 5, 'msdevlab', 'Fast-paced space missions give it some entertainment value, though the focus seems more mechanical than character-based.', null);  # 313498 Star Wars: Rogue Squadron 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313503, 6, 'msdevlab', 'Animated action adds energy and makes the world accessible, but the format feels smaller and less emotionally powerful.', null);  # 313503 Star Wars: The Clone Wars 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313504, 5, 'msdevlab', 'Some adventure appeal remains, although this record feels older and less engaging as a standalone viewing choice.', null);  # 313504 Star Wars: The Empire Strikes Back 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313506, 4, 'msdevlab', 'Pilot-focused sci-fi action is not enough on its own, since the record seems to offer little personal or emotional story.', null);  # 313506 Star Wars: X-Wing 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313508, 4, 'msdevlab', 'The combat concept may suit fans of the universe, but it does not feel like a movie that would be very memorable personally.', null);  # 313508 Star Wars: X-Wing vs. TIE Fighter 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (113506, 5, 'msdevlab', 'Gentle emotion gives the film charm, but the slower pace makes it only moderately engaging for this profile.', null);  # 113506 Finding Neverland 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194492, 5, 'msdevlab', 'Fantasy world is appealing, but this version would probably feel less immersive and harder to connect with.', null);  # 194492 Lord of the Rings 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194495, 8, 'msdevlab', 'The epic scale and emotional loyalty between the characters make the fantasy feel impressive and meaningful.', null);  # 194495 Lord of the Rings: Return of the King, The (2003/II) 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194496, 5, 'msdevlab', 'Fantasy world is appealing, but this record appears to be a side/game title with limited movie-style storytelling.', null);  # 194496 Lord of the Rings: The Battle for Middle-Earth, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194497, 8, 'msdevlab', 'Journey has a clear purpose, strong friendships, and enough adventure to keep the fantasy meaningful.', null);  # 194497 Lord of the Rings: The Fellowship of the Ring, The 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194498, 7, 'msdevlab', 'Fantasy adventure has clear stakes and strong friendships, which gives the story emotional value.', null);  # 194498 Lord of the Rings: The Fellowship of the Ring, The 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194499, 5, 'msdevlab', 'Fantasy world is appealing, but this record appears to be a side/game title with limited movie-style storytelling.', null);  # 194499 Lord of the Rings: The Quest Fulfilled, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194500, 7, 'msdevlab', 'Fantasy adventure has clear stakes and strong friendships, which gives the story emotional value.', null);  # 194500 Lord of the Rings: The Return of the King, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194501, 5, 'msdevlab', 'Fantasy world is appealing, but this record appears to be a side/game title with limited movie-style storytelling.', null);  # 194501 Lord of the Rings: The Third Age 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194502, 8, 'msdevlab', 'The battles feel effective because they are connected to a bigger story, not just action for its own sake.', null);  # 194502 Lord of the Rings: The Two Towers, The 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194503, 7, 'msdevlab', 'Fantasy adventure has clear stakes and strong friendships, which gives the story emotional value.', null);  # 194503 Lord of the Rings: The Two Towers, The (2002/II) 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194504, 5, 'msdevlab', 'Fantasy world is appealing, but this record appears to be a side/game title with limited movie-style storytelling.', null);  # 194504 Lord of the Rings: The War of the Ring, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (264157, 7, 'msdevlab', 'It is light and romantic in a pleasant way, though it can feel a little predictable and fairytale-like.', null);  # 264157 Princess Diaries 2: Royal Engagement, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300229, 9, 'msdevlab', 'The humor supports a real story, and the characters are charming without making the movie feel childish.', null);  # 300229 Shrek 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300230, 9, 'msdevlab', 'Sequel keeps the clever humor and adds even stronger character moments, so it stays very enjoyable.', null);  # 300230 Shrek 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300233, 5, 'msdevlab', 'Shrek’s humor is still recognizable here, but the short attraction-style format makes it feel less satisfying as a movie.', null);  # 300233 Shrek 4-D 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311604, 3, 'msdevlab', 'This feels too childish and game-like, with limited story depth.', null);  # 311604 SpongeBob SquarePants: Legend of the Lost Spatula 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311606, 3, 'msdevlab', 'Humor is probably too silly, and the record does not seem strongly plot-driven.', null);  # 311606 SpongeBob SquarePants: Revenge of the Flying Dutchman 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311607, 3, 'msdevlab', 'This is too childish and not the kind of animated story that feels engaging.', null);  # 311607 SpongeBob SquarePants: SuperSponge 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (340652, 7, 'msdevlab', 'Large-scale action and drama are appealing, though the historical style is not a natural favorite.', null);  # 340652 Troy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (405119, 4, 'msdevlab', 'A clear mystery can be enjoyable, but this version is probably too old-fashioned.', null);  # 405119 Sherlock Holmes 1951
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (406158, 4, 'msdevlab', 'Superhero elements are appealing, but this version feels too limited and less polished as a full movie experience.', null);  # 406158 Spider-Man 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (406411, 6, 'msdevlab', 'Stylized animated battles are enjoyable in parts, but the shorter format limits character depth and emotional impact.', null);  # 406411 Star Wars: Clone Wars 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (849, 2, 'msdevlab', 'This is exactly the type of childish family movie that feels less appealing.', null);  # 849 101 Dalmatians II: Patch's London Adventure 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (850, 1, 'msdevlab', 'A sing-along version has almost none of the plot or emotional stakes expected from a movie.', null);  # 850 101 Dalmatians Sing Along 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30972, 5, 'msdevlab', 'Batman’s darker atmosphere has some appeal, but the record feels less clear and not fully satisfying as a story.', null);  # 30972 Batman: Dark Justice 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30974, 5, 'msdevlab', 'Superhero tone could work, but this looks closer to a short fan-style record, with limited full-movie impact.', null);  # 30974 Batman: Dead End 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (32180, 5, 'msdevlab', 'A pleasant fairytale setting helps, although the style feels more childish and less personally engaging.', null);  # 32180 Beauty and the Beast 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (151616, 8, 'msdevlab', 'Romantic comedy works because the chemistry is fun and the story has structure beyond jokes.', null);  # 151616 How to Lose a Guy in 10 Days 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (170721, 4, 'msdevlab', 'This feels clearly child-focused, so the story depth is limited.', null);  # 170721 Jungle Book 2, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56871, 8, 'msdevlab', 'The fast pace and character-driven crime story make the movie smart, entertaining, and easy to follow.', null);  # 56871 Catch Me If You Can 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (185176, 4, 'msdevlab', 'Emotional drama is present, but the story does not feel distinctive enough to leave a strong impression.', null);  # 185176 Last Dance 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (190869, 7, 'msdevlab', 'Emotional family theme gives it heart, even if the overall tone stays very light.', null);  # 190869 Lilo & Stitch 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (200864, 6, 'msdevlab', 'Romantic elements are easy to watch, but the plot is fairly predictable and not especially fresh.', null);  # 200864 Maid in Manhattan 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (14132, 4, 'msdevlab', 'This seems too dependent on crude comedy, while the plot does not sound strong enough.', null);  # 14132 American Pie 2 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (109421, 9, 'msdevlab', 'The cars, action, loyalty, and fast pace make this a very strong fit for this profile.', null);  # 109421 Fast and the Furious, The 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (129185, 8, 'msdevlab', 'Action has emotional purpose and a strong main character, which makes the drama feel meaningful.', null);  # 129185 Gladiator 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (644, 8, 'msdevlab', 'Romantic comedy feels witty and character-driven, not just predictable or childish.', null);  # 644 10 Things I Hate About You 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210739, 8, 'msdevlab', 'Will Smith, humor, action, and a clear sci-fi story make this very enjoyable.', null);  # 210739 Men in Black 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (333856, 10, 'msdevlab', 'The emotional scale, romance, and unforgettable disaster storyline make it powerful despite its older release year.', null);  # 333856 Titanic 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (158999, 9, 'msdevlab', 'The large-scale threat and heroic action make it entertaining, with enough emotion to support the spectacle.', null);  # 158999 Independence Day 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56304, 5, 'msdevlab', 'Crime drama gives the movie substance, although the long, colder style is less aligned with this taste profile.', null);  # 56304 Casino 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (66194, 7, 'msdevlab', 'The teen comedy style is light and memorable, but the story still has enough charm to stay enjoyable.', null);  # 66194 Clueless 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (337166, 6, 'msdevlab', 'Warm characters and a creative concept work well, though the very family-oriented tone keeps the rating moderate.', null);  # 337166 Toy Story 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (290070, 6, 'msdevlab', 'Historical importance and emotional weight are clear, but the heavy tone makes it less personally rewatchable.', null);  # 290070 Schindler's List 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131780, 7, 'msdevlab', 'Storytelling is strong and interesting, though the crime style is less close to the usual favorites.', null);  # 131780 Goodfellas 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (263360, 8, 'msdevlab', 'Romance is charming and iconic, with strong chemistry and an easy-to-follow story.', null);  # 263360 Pretty Woman 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280305, 5, 'msdevlab', 'Sport-drama elements are still watchable, yet the story feels less inspiring and less energetic here.', null);  # 280305 Rocky V 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (189403, 5, 'msdevlab', 'Classic spy action is present, but the older style makes the movie feel less exciting today.', null);  # 189403 Licence to Kill 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188511, 7, 'msdevlab', 'Buddy-action energy is fun, and the character chemistry gives the movie real personality beyond the fights.', null);  # 188511 Lethal Weapon 4 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335835, 8, 'msdevlab', 'Action, confidence, and Tom Cruise make it very watchable.', null);  # 335835 Top Gun 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311428, 5, 'msdevlab', 'A charming romantic fantasy idea helps, although the older pacing makes the movie only mildly engaging.', null);  # 311428 Splash 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (96593, 6, 'msdevlab', 'Emotional connection is strong in places, but the older family-adventure style keeps it from ranking higher.', null);  # 96593 E.T. the Extra-Terrestrial 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (271095, 8, 'msdevlab', 'Adventure still feels clear and exciting, with a hero who is easy to follow.', null);  # 271095 Raiders of the Lost Ark 1981
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (165961, 5, 'msdevlab', 'It is iconic, but the horror-thriller element and slower pacing reduce its appeal.', null);  # 165961 Jaws 1975
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10945, 4, 'msdevlab', 'Sci-fi idea is interesting, but the horror atmosphere does not fit the preferred style.', null);  # 10945 Alien 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (14477, 5, 'msdevlab', 'Historical drama gives the movie meaning, although the slower tone makes it less naturally enjoyable for this profile.', null);  # 14477 Amistad 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30686, 5, 'msdevlab', 'Drama may be strong, but the darker realistic tone makes it less enjoyable.', null);  # 30686 Basketball Diaries, The 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (34077, 5, 'msdevlab', 'An unusual life story is interesting, but the slower emotional pacing makes it feel a bit distant.', null);  # 34077 Benjamin Button 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (34104, 5, 'msdevlab', 'Sweet character moments help the film, although the story feels quieter than the movies that usually score higher here.', null);  # 34104 Benny & Joon 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (39551, 7, 'msdevlab', 'Intense action has a serious purpose, though the war setting makes it very heavy.', null);  # 39551 Black Hawk Down 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (41518, 5, 'msdevlab', 'Crime-drama energy is present, but the heavier tone and less relatable characters keep the rating moderate.', null);  # 41518 Blow 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46167, 5, 'msdevlab', 'This sounds serious and less entertaining, with limited connection to the preferred adventure style.', null);  # 46167 Brave, The 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46169, 8, 'msdevlab', 'Epic action has emotion, loyalty, and high stakes, which makes it easier to connect with.', null);  # 46169 Braveheart 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46878, 6, 'msdevlab', 'Romantic comedy elements are enjoyable, though some moments feel too silly and uneven to score higher.', null);  # 46878 Bridget Jones: The Edge of Reason 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (54209, 3, 'msdevlab', 'Thriller-horror feeling is too uncomfortable, even if the movie is well-known.', null);  # 54209 Cape Fear 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (62460, 6, 'msdevlab', 'Atmosphere seems warm and charming, but the pace is probably too slow.', null);  # 62460 Chocolat 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (86263, 7, 'msdevlab', 'Spy-action style is enjoyable, although the story does not feel fully grounded.', null);  # 86263 Die Another Day 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (112290, 5, 'msdevlab', 'The concept is intriguing and memorable, but the darker psychological tone makes it less naturally enjoyable.', null);  # 112290 Fight Club 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120506, 3, 'msdevlab', 'Horror-crime atmosphere does not fit the preferred style of suspense.', null);  # 120506 From Hell 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (123435, 6, 'msdevlab', 'Mystery keeps the movie engaging, although the colder style makes it harder to connect emotionally.', null);  # 123435 Game, The 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (123849, 5, 'msdevlab', 'Historical scale gives the film substance, but the heavy pacing makes it less naturally enjoyable.', null);  # 123849 Gangs of New York 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (142491, 7, 'msdevlab', 'Superhero fantasy is fun and unusual, with enough character personality to keep it entertaining.', null);  # 142491 Hellboy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (142492, 7, 'msdevlab', 'Fantasy visuals and action are enjoyable, though the weirdness makes it slightly less relatable.', null);  # 142492 Hellboy 2 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176711, 5, 'msdevlab', 'Stylized action is memorable, though the violence-driven tone is less aligned with the preferred kind of action.', null);  # 176711 Kill Bill: Vol. 1 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176712, 5, 'msdevlab', 'Character focus adds more depth, but the style still feels too harsh to become a top preference.', null);  # 176712 Kill Bill: Vol. 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (178994, 5, 'msdevlab', 'Crime-action idea is fine, but it does not sound memorable enough for a higher rating.', null);  # 178994 Knockaround Guys 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (185628, 8, 'msdevlab', 'Action has emotion, culture, and a strong personal journey, which makes it more meaningful.', null);  # 185628 Last Samurai, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (192850, 4, 'msdevlab', 'This does not sound like a movie style that would feel especially memorable.', null);  # 192850 Lizzie 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (200521, 5, 'msdevlab', 'Film may be deep, but it seems too long and abstract for a clear, satisfying experience.', null);  # 200521 Magnolia 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210511, 6, 'msdevlab', 'The puzzle structure is interesting and requires thought, while still giving the story a clear purpose.', null);  # 210511 Memento 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (214755, 8, 'msdevlab', 'Sci-fi action has a clear idea, strong suspense, and Tom Cruise, making it a good fit.', null);  # 214755 Minority Report 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238072, 8, 'msdevlab', 'The stylish heist plot, strong cast, and smooth pacing make it entertaining without feeling empty.', null);  # 238072 Ocean's Eleven 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238073, 7, 'msdevlab', 'Cast is fun, but the story does not sound sharp and satisfying enough.', null);  # 238073 Ocean's Twelve 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (244421, 5, 'msdevlab', 'Emotional drama may be sweet, but it does not strongly match the genres that create excitement.', null);  # 244421 Other Sister, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (245699, 5, 'msdevlab', 'Romantic comedy elements have charm, but the older style and simple setup keep the score moderate.', null);  # 245699 Overboard 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (247579, 7, 'msdevlab', 'Suspense is clear and focused, though the darker thriller tone lowers the rating slightly.', null);  # 247579 Panic Room 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256839, 5, 'msdevlab', 'Sci-fi action could be interesting, but the horror elements reduce its appeal.', null);  # 256839 Pitch Black 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (271344, 5, 'msdevlab', 'Family drama and warmth are present, although the story feels a bit predictable overall.', null);  # 271344 Raising Helen 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (292671, 4, 'msdevlab', 'Psychological thriller style feels too dark for the preferred type of suspense.', null);  # 292671 Secret Window 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (306032, 5, 'msdevlab', 'Crime comedy has style and energy, but the humor and tone feel less personally accessible.', null);  # 306032 Snatch. 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (310168, 4, 'msdevlab', 'A documentary-style record is interesting, but it lacks the characters and story expected from a movie.', null);  # 310168 Space Station 3D 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312150, 5, 'msdevlab', 'Adventure is energetic, but the tone is too childish for a strong rating.', null);  # 312150 Spy Kids 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312151, 4, 'msdevlab', 'Sequel feels even more child-focused, so it would not be a strong personal favorite.', null);  # 312151 Spy Kids 2: Island of Lost Dreams 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312152, 3, 'msdevlab', 'This sounds too gimmicky and childish, with limited meaningful plot.', null);  # 312152 Spy Kids 3-D: Game Over 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (319602, 5, 'msdevlab', 'Superhero foundations are clear, though the older pacing and effects make it feel less exciting now.', null);  # 319602 Superman 1978
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (319613, 5, 'msdevlab', 'Heroic moments still work, but the older style makes the movie feel only moderately engaging.', null);  # 319613 Superman II 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (328272, 7, 'msdevlab', 'Character is easy to care about, and the story has warmth even without big action.', null);  # 328272 Terminal, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (328666, 3, 'msdevlab', 'This seems like a comedy sketch record, with too little real plot.', null);  # 328666 Terry Tate, Office Linebacker 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335336, 6, 'msdevlab', 'Spy action keeps the movie watchable, although the story does not feel especially fresh or emotional.', null);  # 335336 Tomorrow Never Dies 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (336445, 4, 'msdevlab', 'This sounds too dramatic and distant from the preferred genres.', null);  # 336445 Total Eclipse 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (342797, 5, 'msdevlab', 'Title suggests a smaller drama or romance, but it does not sound especially memorable.', null);  # 342797 Two Days with Juliet 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (350424, 5, 'msdevlab', 'An intriguing concept helps, but the confusing tone makes the movie harder to enjoy consistently.', null);  # 350424 Vanilla Sky 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (359297, 8, 'msdevlab', 'Disaster sci-fi action is intense and easy to follow, which makes it a good fit.', null);  # 359297 War of the Worlds 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (368418, 6, 'msdevlab', 'Action and spy elements are present, though the plot feels too standard to stand out strongly.', null);  # 368418 World Is Not Enough, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (370017, 7, 'msdevlab', 'Action is fast and energetic, but the story does not sound meaningful enough for a higher rating.', null);  # 370017 XXX 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (371305, 4, 'msdevlab', 'This record does not sound like a clear match for the preferred genres or story types.', null);  # 371305 Yes and 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30955, 6, 'msdevlab', 'Batman’s atmosphere is appealing, but the older style makes the movie feel less personally exciting.', null);  # 30955 Batman 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30959, 9, 'msdevlab', 'The darker superhero origin story gives the action more meaning and makes the character easier to connect with.', null);  # 30959 Batman Begins 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30965, 5, 'msdevlab', 'Colorful superhero entertainment works in parts, though the tone feels too uneven and exaggerated.', null);  # 30965 Batman Forever 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30967, 5, 'msdevlab', 'Darker visuals create interest, but the older pacing makes the story less engaging overall.', null);  # 30967 Batman Returns 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30976, 5, 'msdevlab', 'Animated Batman storytelling has some depth, although the format feels less personally exciting as a movie choice.', null);  # 30976 Batman: Mask of the Phantasm 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (381392, 5, 'msdevlab', 'A futuristic superhero idea is interesting, but it feels more like television-style entertainment than a strong film experience.', null);  # 381392 Batman Beyond 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10920, 5, 'msdevlab', 'Action element is strong, but the scary sci-fi atmosphere still makes it less enjoyable.', null);  # 10920 Aliens 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (40199, 5, 'msdevlab', 'Sci-fi world is famous, but the slow and abstract style is not ideal.', null);  # 40199 Blade Runner 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (65811, 5, 'msdevlab', 'Idea is interesting, but the older pacing would probably make it harder to stay engaged.', null);  # 65811 Close Encounters of the Third Kind 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (21213, 5, 'msdevlab', 'Science-fiction ideas are meaningful, yet the slow and distant tone makes the movie less easy to connect with.', null);  # 21213 Artificial Intelligence: AI 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (61751, 6, 'msdevlab', 'The dystopian setting is serious and thought-provoking, though the heavy tone makes it less easy to enjoy casually.', null);  # 61751 Children of Men, The 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (267038, 6, 'msdevlab', 'Movie is iconic and clever, but the fragmented style makes it less clear and less easy to enjoy.', null);  # 267038 Pulp Fiction 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (276217, 5, 'msdevlab', 'Crime style is sharp, but it feels too dialogue-heavy and violent for this profile.', null);  # 276217 Reservoir Dogs 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (297838, 8, 'msdevlab', 'The emotional storytelling and strong character journey make it meaningful, even with a slower pace.', null);  # 297838 Shawshank Redemption, The 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (289109, 6, 'msdevlab', 'A war story with emotional weight is clear, but the heavy and intense tone keeps it from being a favorite.', null);  # 289109 Saving Private Ryan 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (326155, 4, 'msdevlab', 'Dark character study is probably too heavy and distant from the preferred style.', null);  # 326155 Taxi Driver 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (270971, 4, 'msdevlab', 'Film may be respected, but the harsh character focus is not appealing enough.', null);  # 270971 Raging Bull 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (291698, 4, 'msdevlab', 'The mystery is intense and memorable, but the dark tone makes it more challenging than purely enjoyable.', null);  # 291698 Se7en 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280270, 6, 'msdevlab', 'The underdog story is inspiring and character-based, which makes the older style easier to connect with.', null);  # 280270 Rocky 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280281, 6, 'msdevlab', 'Motivational drama still works, but the style feels somewhat dated and less gripping.', null);  # 280281 Rocky II 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280282, 6, 'msdevlab', 'Training and comeback energy are enjoyable, though the movie feels a little simple overall.', null);  # 280282 Rocky III 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280284, 8, 'msdevlab', 'Movie is dramatic and energetic, with a clear conflict that makes the action feel exciting.', null);  # 280284 Rocky IV 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188507, 6, 'msdevlab', 'The buddy-action dynamic adds energy and humor, while the crime plot keeps the movie moving.', null);  # 188507 Lethal Weapon 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188509, 6, 'msdevlab', 'Action and chemistry are enjoyable, though the formula feels fairly familiar.', null);  # 188509 Lethal Weapon 2 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188510, 6, 'msdevlab', 'Fast buddy-cop energy is present, but the story feels more standard than truly memorable.', null);  # 188510 Lethal Weapon 3 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (92573, 4, 'msdevlab', 'Spy concept is appealing, but the style feels too old-fashioned.', null);  # 92573 Dr. No 1962
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120574, 4, 'msdevlab', 'Classic spy style is important, but the pacing and age reduce enjoyment.', null);  # 120574 From Russia with Love 1963
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (130953, 5, 'msdevlab', 'Movie is iconic, but the style feels too dated for a strong rating.', null);  # 130953 Goldfinger 1964
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (332065, 4, 'msdevlab', 'Spy adventure would probably feel too slow and dated.', null);  # 332065 Thunderball 1965
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (85871, 4, 'msdevlab', 'Spy formula is present, but the dated tone makes it hard to connect.', null);  # 85871 Diamonds Are Forever 1971
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (117314, 5, 'msdevlab', 'Action-spy plot has some appeal, though the older style limits the enjoyment.', null);  # 117314 For Your Eyes Only 1981
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (192514, 4, 'msdevlab', 'Spy concept is fine, but the age and tone reduce the appeal.', null);  # 192514 Live and Let Die 1973
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (203649, 4, 'msdevlab', 'Premise sounds memorable, but the older execution would probably feel less exciting.', null);  # 203649 Man with the Golden Gun, The 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (218808, 5, 'msdevlab', 'Space-action idea is fun, but the older spy style can feel silly instead of genuinely thrilling.', null);  # 218808 Moonraker 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (240521, 5, 'msdevlab', 'Romance angle adds interest, but the older style limits the overall appeal.', null);  # 240521 On Her Majesty's Secret Service 1969
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312170, 5, 'msdevlab', 'Spy adventure has some entertainment value, but the dated pacing lowers the rating.', null);  # 312170 Spy Who Loved Me, The 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (354178, 5, 'msdevlab', 'Action premise is okay, but the older spy formula would not be a top choice.', null);  # 354178 View to a Kill, A 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (372233, 4, 'msdevlab', 'Spy-adventure genre has some appeal, but the movie feels too dated.', null);  # 372233 You Only Live Twice 1967
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (164572, 5, 'msdevlab', 'Crime style and dialogue have appeal, but the slower rhythm makes the movie less engaging for this profile.', null);  # 164572 Jackie Brown 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (118367, 5, 'msdevlab', 'Unusual comedy style sounds creative, but it may feel too random and not plot-driven enough.', null);  # 118367 Four Rooms 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (209158, 4, 'msdevlab', 'Old crime-drama style is probably too slow and distant from the preferred genres.', null);  # 209158 Mean Streets 1973
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131885, 6, 'msdevlab', 'Adventure is fun and nostalgic, but the child-focused tone keeps it from being a higher score.', null);  # 131885 Goonies, The 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (149287, 6, 'msdevlab', 'Adventure and nostalgia are pleasant, although the family tone feels a bit too childish in places.', null);  # 149287 Hook 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (97360, 5, 'msdevlab', 'Film may be interesting, but the old Hollywood subject does not strongly match the preferred style.', null);  # 97360 Ed Wood 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (97727, 7, 'msdevlab', 'Fantasy is strange but emotional, and the main character is easy to feel for.', null);  # 97727 Edward Scissorhands 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (304862, 4, 'msdevlab', 'Gothic horror atmosphere is not appealing, even though the visuals may be memorable.', null);  # 304862 Sleepy Hollow 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (70959, 6, 'msdevlab', 'Animation is creative, but the dark gothic tone is less appealing.', null);  # 70959 Corpse Bride, The 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (220276, 6, 'msdevlab', 'The visual style and music create strong energy, although the dramatic tone may feel a little overwhelming.', null);  # 220276 Moulin Rouge! 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (218219, 6, 'msdevlab', 'Fantasy world-building is impressive, though the heavier animated style feels less personally accessible.', null);  # 218219 Mononoke-hime 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (25192, 5, 'msdevlab', 'Biographical drama has polish, but the slower pace and distant character focus keep the rating moderate.', null);  # 25192 Aviator, The 2004
